### ISSUE TITLE
Preview does not show "lead" markup

### ISSUE THREAD

**Issue by kkamegawa** [atsushieno/vscode-language-review#10]
If add "lead" markup, re:view previewer does not shows preview

```
 //lead{
    This is lead sentence. 
 //}
```

**Comment by atsushieno** [comment]
Sorry for the late response!

I think `lead` just works fine. Isn't it the case that you tried to add `lead` as the first non-whitespace content on your Re:VIEW source? Only top-level header (`=`) works (which I think is Re:VIEW syntax design; at least review.js behaves so).

**Comment by atsushieno** [comment]
I'm marking this as duplicate to https://github.com/atsushieno/vscode-language-review/issues/6
