### ISSUE TITLE
preview fails with "This node is not HeadlineSyntaxTree, actual InlineElementSyntaxTree" message

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/vscode-language-review#15]
There seems to be a regression at 0782dc0 that the parser now fails to process (probably some kind of) nodes in unexpected way.

> Unable to open '/sources/Books/TechBooster/C93-Android/articles/atsushieno.re': this node is not HeadlineSyntaxTree, actual InlineElementSyntaxTree.

**Comment by atsushieno** [comment]
@muojp if you have time can you please have a look?

I can push a reverted release if it's not easy to fix.

**Comment by muojp** [comment]
@atsushieno I'm sorry to getting back to you late. I took a look at the code and found inline `hd` elements are the cause. I made a fix and composed WIP PR #16, willing to un-WIP it when I finished regression testing against more .re docs.

**Comment by atsushieno** [comment]
Thank you for taking a look at it!

**Comment by atsushieno** [comment]
The commit was temporarilly? reverted so there is no need to keep this open.
