### ISSUE TITLE
Breadcrumbs feature have several flaws

### ISSUE THREAD

**Issue by muojp** [atsushieno/vscode-language-review#19]
vscode 1.27 adds functionality to highlight regions during breadcrumbs navigation: https://code.visualstudio.com/updates/v1_27#_breadcrumbs-improvements

It made me notice couple of flaws on current vscode-language-review implementation.

## Range information of symbols are incorrect if the file ends with non-column element (i.e. headline)

I don't get why I didn't notice when implemented this :confused: 

![screenshot from 2018-09-07 16-51-47](https://user-images.githubusercontent.com/766864/45205833-5686b800-b2be-11e8-84c0-2235a17333a6.png)

## Column boundaries are inaccurate

Upstream review.js returns "the next element's starting position" as an ending position of columns. Actually I noticed it before but thought it's a harmless overlapping. But situation changed with the new highlight feature.

![screenshot from 2018-09-07 16-26-56](https://user-images.githubusercontent.com/766864/45205374-e88dc100-b2bc-11e8-8c0f-2c58707fe073.png)

Now vscode-language-review shows as if each column have extra 1 line.

```
= test doc

== foo

aaaaa

== bar

aaaaaggg

gaarfawe

aher

=== bar-sub

sub

====[column] bar-sub-column

column

text

text

====[/column]

aaaaa

bbbb
```

**Comment by atsushieno** [comment]
The fix is merged.
