### ISSUE TITLE
構文チェックで未サポートの改行制御系はエラーではなく無視してほしい

### ISSUE THREAD

**Issue by akira345** [atsushieno/vscode-language-review#21]
VSCodeのプラグインでプレビュー的に使用しているとき、改ページなど未サポートの改行制御系構文がエラーで表示できなくなります。

そもそも表示仕様としてWebページ出力なので、ページの概念がないので用途が違うのですが、
次の改行制御系構文はエラーではなく無視するようにできないでしょうか？

```
//linebreak
    改行
//pagebreak
    改ページ
```

**Comment by atsushieno** [comment]
Re:VIEW構文解析については、このextensionでは実装していなくて、  https://github.com/vvakame/review.js のほうで実装されているものなので、そちらのほうに報告していただければと思います。（構文解析の結果を表示するやり方などはextensionの問題なのでわたしが対応できます。）

（reviewjsも開発は継続していない状態なので対応してもらえるかどうかはわかりません）

ただ、そもそも `//linebreak` `//pagebreak` といった命令はRe:VIEWの公式ドキュメントに記載されていないようです。 https://github.com/kmuto/review/blob/master/doc/format.ja.md

**Comment by akira345** [comment]
なるほど。了解いたしました。
構文については、検索で次の内容が見つかり、これで動作したため構文だと思いました。
https://github.com/repeatedly/ReVIEW/blob/master/doc/format.txt

たしかに公式には記載がないですね。

＞（reviewjsも開発は継続していない状態なので対応してもらえるかどうかはわかりません）
確かに３年くらい止まってますね。

本件はこれでクローズでOKです。お手数をおかけしました。

**Comment by atsushieno** [comment]
なるほどー。 repeatedly/ReVIEW はどういうリポジトリなのかなと思って見てみましたが、READMEにこういう記述があるので、もしかしたら独自拡張なのかもしれませんね。

```
ReVIEW(執筆支援ツール)
=====================

このツールは青木さんが公開されている ReVIEW を私(nari)がちょっとだけ拡
張したものです。
```

あと、review.jsは、vvakameがちょっと開発のアプローチをまるっと変えたいみたいなことを考えたりもしていて、確かにJSの独自実装で新機能に追従していくのはつらいので、こっちには動きがない状態です。必然的にこのextensionもどんどん古くなっていくので、reviewそのものをセットアップして使う erukiti/ya-language-review を使う手もアリです（このリポジトリのREADMEでもリンクしています）。

**Comment by akira345** [comment]
>reviewそのものをセットアップして使う erukiti/ya-language-review を使う手もアリです（このリポジトリのREADMEでもリンクしています）

ご案内ありがとうございます。
これ、自分の環境(Windows10 + Ruby2.5 + ReView2.5.0) だと何故か画像が表示されないのと、prhを併用したかったので、本拡張を利用させてもらってます。

プレビュー表示されなくても、リアルタイムで構文チェック＆揺らぎチェックしてくれるのでかなり助かっています。
