### ISSUE TITLE
Block instructions for enclosed articles do not work and are displayed as non-compliant.

### ISSUE THREAD

**Issue by TakamiChie** [atsushieno/vscode-language-review#22]
# steps
1. Make the following description in the. *.re file.
```review:ch-01.re
//note[test] {
test
//}
```
2. Show live preview from the "Show preview" button.

# problem

In step 1, the line that wrote the note is highlighted as an error line, and you receive the following message:
```
note というブロック構文はサポートされていません。
```

Also, you do not see a live preview in step 2.

However, note notation is supported in Re:view, the following command is not an error, HTML is output.
```powershell: Command
> review compile--target html ch-01.re
```

# expected behavior

"//note"The command is not an error and the live preview is displayed.

# check around
The following command also displayed the row as an error and did not show a live preview.

* //memo[caption]{ ... //}
* //tip[caption]{ ... //}
* //info[caption]{ ... //}
* //warning[caption]{ ... //}
* //important[caption]{ ... //}
* //caution[caption]{ ... //}
* //notice[caption]{ ... //}

Also, if you omit the caption, it was an error.

# reference specifications
Re:VIEW Format Guide>Short column
https://github.com/kmuto/review/blob/master/doc/format.md#short-column

# version
* PC: Windows 10 Home Ver 1809  Build 17763.316
* Visual Studio Code: 1.31.1
* Installed Re:View Version: 3.0
* Installed This Extension Version: 0.4.8

**Comment by atsushieno** [comment]
Thanks for the report. Unfortunately it is an upstream issue at https://github.com/vvakame/review.js which does the actual content validation, namely at: https://github.com/vvakame/review.js/blob/4cfcc64b7ccfd6445059631b0439b26542f0e449/lib/parser/validator.ts#L91

Reports would be welcomed upstream, but I have to say, review.js is quite old and not actively maintained. Yet it is an essential dependency that this entire VSCode extension cannot live without (not depending on it means an entire rewrite of the parser, which is not easily doable).

If you need up-to-date syntax support, https://github.com/erukiti/ya-language-review would work.

**Comment by TakamiChie** [comment]
Thank you for the answer. The contents were reported to the review.js repository.

**Comment by atsushieno** [comment]
It is fixed upstream, and now we have rebased review.js to 0.16.0 which I believe contains the fix. Thanks again for the report.
