### ISSUE TITLE
[proposal]User settings support

### ISSUE THREAD

**Issue by yfakariya** [atsushieno/vscode-language-review#32]
There are some hard coded settings which are needed to be changed per users.
I think that we should determine: 1) whether we should introduce configs or not; 2) prefix and hierarchy of the settings.

* Preview window timer time (currently 1000ms) https://github.com/atsushieno/vscode-language-review/blob/d390cfe0bb20fad0c47f618ed84b7caf4986eb41/src/preview.ts#L336
* CSS to use preview window (related to #25) https://github.com/atsushieno/vscode-language-review/blob/d390cfe0bb20fad0c47f618ed84b7caf4986eb41/src/preview.ts#L52

Related documents:
* [API reference](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration)
  * As far as I experimented, "section name" means first segment of property which is delimited by `.`.
* [package.config reference](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration)

**Comment by atsushieno** [comment]
Thanks for the suggestion. They can be anything, but it you'd like to have some suggestions...

- settings prefix: Maybe simple `language_review` would be good enough? "review" is likely easy to conflict with other extensions.
- preview update period: it is definitely a hack constant without any particular reason for 1000, but is it really something we want customization? Maybe `preview_update_duration` if we indeed need it ?
- custom stylesheet: `preview_css_file` maybe ? It is possible that we want to extended it for absolute URL too, but wouldn't be too confusing to reuse the same settings.

**Comment by yfakariya** [comment]
Thank you for the answer.

* The prefix `language_review` and other names looks good, but they should be for separated camelCasing according to the document. So, I think `languageReview` is better.
* I would propose introducing `preview.` group for these options. The scheme will be reflected vscode's settings screen (see "properties" subsection of the [docs](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) for details).
* I will try to tweak `updateDuration` my local environment and measure load of refresh. I am starting translation of a book, it should be good environment to judge whether the tweak is really needed.
* I agree that restricting css path to simple file name is good start point. We should concern about security when we allow css files which are not located in the local workspace.

**Comment by atsushieno** [comment]
Forgot to close this after https://github.com/atsushieno/vscode-language-review/pull/33 was merged.
