### ISSUE TITLE
Unable to show preview without UAC elevation

### ISSUE THREAD

**Issue by yukitos** [atsushieno/vscode-language-review#4]
I think that the reason of this issue is that an html file for preview is always created under VSCode installed directory.
![image](https://cloud.githubusercontent.com/assets/1076180/21739288/d897fe80-d4da-11e6-8576-7f71b6566152.png)

When I run the VSCode as administrator, I can see the preview correctly, however it should be avoid to use the installation folder as a temporary working space.

**Comment by atsushieno** [comment]
Whoa, I just noticed your issues. Am sorry for that. BTW this should have been fixed  at e4cdd9e.

**Comment by yukitos** [comment]
Good to hear that. Thank you!
