### ISSUE TITLE
Preview may not be displayed in some cases

### ISSUE THREAD

**Issue by nuitsjp** [atsushieno/vscode-language-review#6]
If it is written as follows, all Preview will be hidden.

```
= =
```

And even if erase the last "=" it will not return.
If delete all, it will be displayed again.

**Comment by atsushieno** [comment]
There should be error indicators that tell you the document is invalid against Re:VIEW syntax (you cannot have two "Level 1" headers), like this sshot:
https://dl.dropboxusercontent.com/u/493047/2017/vscode-language-review-issue6.png

The current version of the extension (actually review.js node module) cannot render preview when there are syntactic errors, so you'll have to fix that first.

It had better be improved, but so far it is an upstream issue :(

**Comment by atsushieno** [comment]
I should make first user experience better.

Starting v0.6.1 we get the following message if there is no output from conversion by review.js. It would work better for both initial state and syntax errors.

![image](https://user-images.githubusercontent.com/53929/89419246-1d864500-d76c-11ea-8952-3ed716418404.png)

With this change I close this issue. Thanks for the report!
